url: http://eratecycle.com

source: public-src

destination: public

exclude: [
  'less'
]

# Site settings
title: "Wordpressya"
email: wordpressya@outlook.com
description: "goto guide for Wordpress mastery"

gems:
  - jekyll-sitemap

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/
  - title: facebook
    url: http://facebook.com/

# Build settings
markdown: kramdown
permalink: pretty
